### ISSUE TITLE
Create labels and annotations to each node during provisioning

### ISSUE THREAD

**Issue by kartoch** [ovh/terraform-ovh-publiccloud-k8s#78]
Each node has a `labels` and `annotations` sections to add metadatas:

```
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"c2:99:fd:ab:3e:bc"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 54.38.91.250
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: 2018-03-29T13:20:04Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: 021668a3-623a-40ef-b15d-ba2a69e74a2f
      beta.kubernetes.io/os: linux
      failure-domain.beta.kubernetes.io/region: GRA3
      failure-domain.beta.kubernetes.io/zone: nova
      kubernetes.io/hostname: k8s-worker-1
```

It would be great to add some metadata by default and based on provisioning configuration.

For instance, one (automatic) could add flavor for each node:

```
openstack.ovh.com/flavor = "s1-8"
```
